#!/usr/bin/expect -f

set force_conservative 0

if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set timeout -1
spawn ./install
match_max 100000
expect -exact "Press \[enter\] to read the license agreement..."
send -- "\r "
expect -exact "Do you agree to the terms of the agreement (yes/no)? "
send -- "yes\r"
expect -exact "Max heap size \[512m-11572m\]?:"
send -- "2048m\r"
expect eof
